FROM node:16
RUN mkdir /app
WORKDIR /app

RUN apt-get update 
RUN apt install nodejs npm -y 
RUN npm install -g typescript -y  
COPY ./server/ .
RUN npm install 
RUN npm run build


#COPY ./server/dist/js/ .
#COPY ./server/package.json ./package.json
#COPY ./server/package-lock.json ./package-lock.json
