name: CI_CD
on:
  push:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Clone reppo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: Install Dependencies
        run : |
          npm install
          yarn install
      - name: Run Testing
        run : npm test --watchAll=false
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/todo-app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}

    
