name: CI_CD
on:
  push:
    branches: docker
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone reppo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: Install Dependencies
        working-directory: ./client
        run : |
          ls -la
          npm install
          ls -la
          yarn version
          yarn install
      - name: Run Testing
        working-directory: ./client
        run : npm test --watchAll=false


    
