name: CI_CD
on:
  push:
    branches: [reserve-brench, master]


jobs:

  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Clone reppo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: Install Dependencies
        run : |
          npm install
          yarn install
      - name: Run Testing
        run : npm test --watchAll=false
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bodya1601/todo:latest
        
  build:
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    env: 
      REACT_APP_HOST: ${{ secrets.SERVER_IP }}
    needs: docker
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Clone reppo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: Install Dependencies
        run : |
          yarn install
          npm install
      - name: Run Build App
        run : |
          npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          directory: client
          push: true
          tags: bodya1601/todo-front:latest

        
        
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    needs: build
    steps:
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.2
        with:
          username: ${{ secrets.USER_NAME }}
          server: ${{ secrets.SERVER_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVET_KEY }}
          local_path: /github/workspace/*
          remote_path: /home/ubuntu/app/
          args: '-o ConnectTimeout=5'


        
