

name: CI_CD


on:
  push:
    branches: docker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          files: client
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: Install Dependencies
        run : |
          yarn install
          npm install
      - name: Run Testing
        run : npm test --watchAll=false


    
